---
url: "http://opendata.toronto.ca/gcc/places_of_interest_wgs84.zip"
extract: "PLACES_OF_INTEREST_WGS84.shp"
data_file: 'data.json'
address:
  addressCountry: CA
  addressLocality: Toronto
  addressRegion: ON
subcategory:
  "Attraction": 
  - "Attractions"
  "Beach": 
  - "Beach"
  - "Beaches"
  "Convention & Trade Centres":
  - "Convention Centre"
  "Featured Park":
  - "Park"
  "Gallery":
  - "Gallery"
  - "Art Gallery"
  "Garden / Conservatory":
  - "Garden"
  - "Conservatory"
  "Landmark":
  - "Landmark"
  "Museum":
  - "Museum"
  "Performing Arts":
  - "Arts"
  - "Performing Arts"
  "Shopping":
  - "Mall"
  - "Shopping Center"
  "Sports / Entertainment Venue":
  - "Sports Bar"
  - "Sports Center"
  "Transportation": 
  - "Mass Transit"
  "Visitor Information":
  - "Visitor Information Centre"
  - "Visitor Information"
  - "VIC"
fix_name:
  "^Toronto Eaton Centre$": "Eaton Centre"
