---
source: "places-of-worship"
url: "http://opendata.toronto.ca/gcc/places_of_worship_wgs84.zip"
extract: "PLACE_OF_WORSHIP_WGS84.shp"
data_file: 'data.json'
address:
  addressCountry: CA
  addressLocality: Toronto
  addressRegion: ON
subcategory:
  "Bahai":
  - "Bahai Temple"
  - "Bahai Place of Worship"
  "Buddhist":
  - "Buddhist Temple"
  - "Buddhist Shrine"
  - "Temple"
  "Catholic":
  - "Catholic Church"
  - "Church"
  "Christian":
  - "Christian Church"
  - "Church"
  "Hindu":
  - "Hindu Temple"
  - "Hindu Shrine"
  - "Mandir"
  - "Temple"
  "Jain":
  - "Jain Temple"
  - "Temple"
  "Jewish":
  - "Synagogue"
  "Muslim":
  - "Mosque"
  "Orthodox":
  - "Orthodox Christian Church"
  - "Orthodox Church"
  - "Church"
  "Other": null
  "Scientology": null
  "Sikh":
  - "Sikh Temple"
  - "Temple"
  "Taoist":
  - "Taoist Temple"
  - "Temple"
  "Unitarian":
  - "Unitarian Church"
  - "Church"
  "Zoroastrian":
  - "Fire Temple"
fix_name:
  "\\bSt[.]\\b": "Saint"
  "\\bSt\\b": "Saint"
  "'S": "'s"
  " C$": " Church"
  " Ch$": " Church"
  " Chu$": " Church"
  " Chur$": " Church"
  " Churc$": " Church"
  " Ctr$": " Centre"
  " Jehovah's Wi": "Jehovah's Witness"
